dstore: validate label

diff --git a/dstore b/dstore
--- a/dstore
+++ b/dstore
@@ -185,8 +185,8 @@ while [ $# -gt 0 ]; do
         :*)
             typeset lbl=$1
             shift
-            if ! echo "$lbl" | grep "^[^[:space:]]*$" >/dev/null 2>&1; then
-                echo >&2 "Invalid label '$lbl'. Must not contain whitespaces."
+            if [ ${#lbl} -eq 1 ] || [ "${lbl//[-A-Za-z0-9_]/}" != ':' ]; then
+                echo >&2 "Invalid label '$lbl'."
                 exit 1
             fi
             if [ "$delete" = "true" ]; then
diff --git a/qc_mini b/qc_mini
--- a/qc_mini
+++ b/qc_mini
@@ -71,6 +71,8 @@
 # dstore -h
 #     Display help.
 #
+# Note: A label starts with a colon and may only contains characters, digits,
+# dash and underscore.
 #
 # PORTABILITY
 # -----------
@@ -147,6 +149,11 @@ dstore()
 
     case "$1" in
         :*)
+            if [ ${#1} -eq 1 ] || [ "${1//[-A-Za-z0-9_]/}" != ':' ]; then
+                echo >&2 "ERROR: Invalid label '$1'."
+                return 1
+            fi
+
             if [ $# -eq 1 ]; then
                 qcm_dir="."
             elif [ $# -eq 2 ]; then
