Better check for --help

diff --git a/dstore b/dstore
--- a/dstore
+++ b/dstore
@@ -17,6 +17,35 @@
 QC_DSTORE_INDEX=$QC_DIR/index.dstore
 
 
+
+show_help()
+{
+    echo "Manually manage content of $QC_DSTORE_INDEX for usage with 'qc'."
+    echo ""
+    echo "Usage:"
+    echo "  dstore"
+    echo "      store current directory"
+    echo "  dstore dirname"
+    echo "      store given directory"
+    echo "  dstore -d"
+    echo "      remove current directory from index"
+    echo "  dstore -d dirname"
+    echo "      remove given directory from index"
+    echo "  dstore :lbl"
+    echo "      store current directory with label ':lbl'"
+    echo "  dstore :lbl dirname"
+    echo "      store given directory with label ':lbl'"
+    echo "  dstore -d :lbl"
+    echo "      remove directory labeled with ':lbl' from index"
+    echo "  dstore [-e | -l | -c]"
+    echo "      '-e'  edit directory index (using ${VISUAL:-${EDITOR:-vi}})"
+    echo "      '-l'  list directory index"
+    echo "      '-c'  clean up duplicate/none-existing entries"
+    echo ""
+    echo "See also: qc --help"
+    echo ""
+}
+
 # cleanup ~/.qc/index.dstore
 function __dstore_clean
 {
@@ -95,6 +124,7 @@ function __qc_fqname
     fi
 }
 
+
 #---------[ MAIN ]-------------------------------------------------------------
 # create ~/.qc/index.dstore if it does not exist.
 [ ! -d "$QC_DIR" ] && mkdir "$QC_DIR"
@@ -120,33 +150,14 @@ while getopts ":elcd" o "$@"; do
         d) delete=true
             ;;
         *)
-            if [[ "$*" != *--help* ]]; then
-                echo >&2 "Invalid option '$OPTARG'" && echo >&2 ""
+            if [ "${!OPTIND}" = "--help" ]; then
+                show_help
+                exit 0
+            else
+                echo >&2 "Invalid option '$OPTARG' in '${!OPTIND}'" && echo >&2 ""
+                show_help
+                exit 1
             fi
-            echo >&2 "Manually manage content of $QC_DSTORE_INDEX for usage with 'qc'."
-            echo >&2 ""
-            echo >&2 "Usage:"
-            echo >&2 "  dstore"
-            echo >&2 "      store current directory"
-            echo >&2 "  dstore dirname"
-            echo >&2 "      store given directory"
-            echo >&2 "  dstore -d"
-            echo >&2 "      remove current directory from index"
-            echo >&2 "  dstore -d dirname"
-            echo >&2 "      remove given directory from index"
-            echo >&2 "  dstore :lbl"
-            echo >&2 "      store current directory with label ':lbl'"
-            echo >&2 "  dstore :lbl dirname"
-            echo >&2 "      store given directory with label ':lbl'"
-            echo >&2 "  dstore -d :lbl"
-            echo >&2 "      remove directory labeled with ':lbl' from index"
-            echo >&2 "  dstore [-e | -l | -c]"
-            echo >&2 "      '-e'  edit directory index (using ${VISUAL:-${EDITOR:-vi}})"
-            echo >&2 "      '-l'  list directory index"
-            echo >&2 "      '-c'  clean up duplicate/none-existing entries"
-            echo >&2 ""
-            echo >&2 "See also: qc --help"
-            echo >&2 ""
             exit
             ;;
     esac
diff --git a/quick-change-directory b/quick-change-directory
--- a/quick-change-directory
+++ b/quick-change-directory
@@ -14,6 +14,62 @@
 # file is managed using the command 'dstore'.
 QC_DSTORE_INDEX=$QC_DIR/index.dstore
 
+show_help()
+{
+    echo "Quick Change -- index based directory changer"
+    echo ""
+    echo "Usage:"
+    echo "  qc [-ie] <dir>"
+    echo "      Search for dir in index and cd to it."
+    echo "      -i  Search case-insensitive (slower)."
+    echo "      -e  Also search extended index."
+    echo "  qc :name"
+    echo "      Search for dir labeled with ':name' in index and cd to it."
+    echo "      Use the command 'dstore' to manage labeled directories."
+    echo "  qc -u [dir...]"
+    echo "      Updates index. If dirs are given only that directories are updated,"
+    echo "      This uses the external command 'qc-build-index.sh'."
+    echo "  qc -U [dir...]"
+    echo "      Like '-u', but also updates extended indexes."
+    echo "  qc -l"
+    echo "      List labeled dirs."
+    echo "  qc -S"
+    echo "      Print statistics of index."
+    echo "  qc -"
+    echo "      Act like 'cd -'."
+    echo "  qc"
+    echo "      Act like 'cd \$HOME'."
+    echo ""
+    echo "Note: qc automatically adds wildcards"
+    echo "  'qc Documents/Adm' searches for '**/Documents/Adm*'"
+    echo "  'qc Doc Adm' searches for '**/Doc*/Adm*'"
+    echo ""
+    echo "See also: dstore --help"
+    echo ""
+    check_initialized
+}
+
+function check_initialized
+{
+    if [ ! -d "$QC_DIR" ] || ! ls -A "$QC_DIR"/*.index >/dev/null 2>&1; then
+        echo "==============================================================================="
+        echo
+        echo "Quick Change Directory not initialized."
+        echo
+        echo "Your home directory needs to be scanned to create a index. Depending on its"
+        echo "size this might take a few minutes."
+        echo
+        echo "Call 'qc -u' or 'qc -U' to create a index of your home directory."
+        echo
+        echo "See 'qc --help' for details."
+        echo
+        echo "==============================================================================="
+        return 1
+    else
+        return 0
+    fi
+}
+
 # Create regex from qc argument
 # Used from qc and completion
 # $*: The pattern to create a regex
@@ -249,61 +305,6 @@ function internalUpdateIndex
     echo "Stored $(wc -l < "$INDEX_FILE") directory names."
 }
 
-show_help()
-{
-    echo "Quick Change -- index based directory changer"
-    echo ""
-    echo "Usage:"
-    echo "  qc [-ie] <dir>"
-    echo "      Search for dir in index and cd to it."
-    echo "      -i  Search case-insensitive (slower)."
-    echo "      -e  Also search extended index."
-    echo "  qc :name"
-    echo "      Search for dir labeled with ':name' in index and cd to it."
-    echo "      Use the command 'dstore' to manage labeled directories."
-    echo "  qc -u [dir...]"
-    echo "      Updates index. If dirs are given only that directories are updated,"
-    echo "      This uses the external command 'qc-build-index.sh'."
-    echo "  qc -U [dir...]"
-    echo "      Like '-u', but also updates extended indexes."
-    echo "  qc -l"
-    echo "      List labeled dirs."
-    echo "  qc -S"
-    echo "      Print statistics of index."
-    echo "  qc -"
-    echo "      Act like 'cd -'."
-    echo "  qc"
-    echo "      Act like 'cd \$HOME'."
-    echo ""
-    echo "Note: qc automatically adds wildcards"
-    echo "  'qc Documents/Adm' searches for '**/Documents/Adm*'"
-    echo "  'qc Doc Adm' searches for '**/Doc*/Adm*'"
-    echo ""
-    echo "See also: dstore --help"
-    echo ""
-    check_initialized
-}
-
-function check_initialized
-{
-    if [ ! -d "$QC_DIR" ] || ! ls -A "$QC_DIR"/*.index >/dev/null 2>&1; then
-        echo "==============================================================================="
-        echo
-        echo "Quick Change Directory not initialized."
-        echo
-        echo "Your home directory needs to be scanned to create a index. Depending on its"
-        echo "size this might take a few minutes."
-        echo
-        echo "Call 'qc -u' or 'qc -U' to create a index of your home directory."
-        echo
-        echo "See 'qc --help' for details."
-        echo
-        echo "==============================================================================="
-        return 1
-    else
-        return 0
-    fi
-}
 
 complete_index_dir()
 {
@@ -423,13 +424,13 @@ while getopts ":ieuUSl" o "$@"; do
             exit 0
             ;;
         *)
-            if [[ "$*" != *--help* ]]; then
-                echo >&2 "Invalid option '$OPTARG'" && echo >&2 ""
-                show_help >&2
-                exit 1
-            else
+            if [ "${!OPTIND}" = "--help" ]; then
                 show_help >&2
                 exit 0
+            else
+                echo >&2 "Invalid option '$OPTARG' in '${!OPTIND}'" && echo >&2 ""
+                show_help >&2
+                exit 1
             fi
             ;;
     esac
