Fixed invalid option handling
Unbound variable again

diff --git a/dstore b/dstore
--- a/dstore
+++ b/dstore
@@ -135,7 +135,7 @@ __qc_fqname()
 typeset delete=''
 typeset OPTIND o
 
-while getopts ":elcd" o "$@"; do
+while getopts ":elcd-" o "$@"; do
     case $o in
         e)
             ${VISUAL:-${EDITOR:-vi}} "$QC_DSTORE_INDEX"
@@ -151,7 +151,7 @@ while getopts ":elcd" o "$@"; do
             ;;
         d) delete=true
             ;;
-        *)
+        -)
             if [ "${!OPTIND}" = "--help" ]; then
                 show_help
                 exit 0
@@ -159,11 +159,16 @@ while getopts ":elcd" o "$@"; do
                 echo "$script_name - Quick Change Directory v$qc_version"
                 exit 0
             else
-                echo >&2 "Invalid option '$OPTARG' in '${!OPTIND}'" && echo >&2 ""
-                show_help >&2
+                echo >&2 "Invalid option '${!OPTIND:-}'" && echo >&2 ""
+                echo >&2 "Try '$script_name --help' for more information."
                 exit 1
             fi
             exit
+            ;;
+        *)
+            echo >&2 "Invalid option '$OPTARG'"
+            echo >&2 "Try '$script_name --help' for more information."
+            exit 1
             ;;
     esac
 done
diff --git a/qc-backend b/qc-backend
--- a/qc-backend
+++ b/qc-backend
@@ -429,7 +429,7 @@ if [ "${1:-}" = "--complete" ]; then
     complete_option "$@"
 fi
 
-while getopts ":ieEuUSl" o "$@"; do
+while getopts ":ieEuUSl-" o "$@"; do
     case $o in
         i) grepOpt="-i"
             ;;
@@ -459,18 +459,24 @@ while getopts ":ieEuUSl" o "$@"; do
             grep --color=always '^:[^ ]* ' "$QC_DSTORE_INDEX" >&2
             exit 0
             ;;
-        *)
-            if [ "${!OPTIND}" = "--help" ]; then
+        -)
+            if [ "${!OPTIND:-}" = "--help" ]; then
                 show_help >&2
                 exit 0
-            elif [ "${!OPTIND}" = "--version" ]; then
+            elif [ "${!OPTIND:-}" = "--version" ]; then
                 echo "qc - Quick Change Directory v$qc_version" >&2
                 exit 0
             else
-                echo >&2 "Invalid option '$OPTARG' in '${!OPTIND}'" && echo >&2 ""
-                show_help >&2
+                echo >&2 "Invalid option '${!OPTIND:-}'"
+                echo >&2 "Try qc --help"
+                echo >&2 "Try 'qc --help' for more information."
                 exit 1
             fi
+            ;;
+        *)
+                echo >&2 "Invalid option '$OPTARG'"
+                echo >&2 "Try 'qc --help' for more information."
+                exit 1
             ;;
     esac
 done
diff --git a/qc-build-index b/qc-build-index
--- a/qc-build-index
+++ b/qc-build-index
@@ -341,7 +341,7 @@ configure_crontab()
 #---------[ MAIN ]-------------------------------------------------------------
 
 typeset -a INC_UPD=()
-while getopts ":Ei:" o "$@"; do
+while getopts ":Ei:-" o "$@"; do
     case $o in
         i)
             d=$OPTARG
@@ -351,7 +351,7 @@ while getopts ":Ei:" o "$@"; do
         E)
             ignExt=true
             ;;
-        *)
+        -)
             if [ "${!OPTIND}" = "--help" ]; then
                 show_help
                 exit 0
@@ -363,10 +363,15 @@ while getopts ":Ei:" o "$@"; do
                 configure_crontab "${!OPTIND:-}"
                 exit
             else
-                echo >&2 "Invalid option '$OPTARG' in '${!OPTIND}'" && echo >&2 ""
-                show_help >&2
+                echo >&2 "Invalid option '${!OPTIND:-}'" && echo >&2 ""
+                echo >&2 "Try '$script_name --help' for more information."
                 exit 1
             fi
+            ;;
+        *)
+            echo >&2 "Invalid option '$OPTARG'"
+            echo >&2 "Try '$script_name --help' for more information."
+            exit 1
             ;;
     esac
 done
