Use getopt instead of shell-internal getopts
Now long options (like --help) are properly handled.
With getopts this was done with a "hack".

The shell-internal getopts is still used in qc_mini and by
qc-build-index when parsing the index definitions in qc-index.cfg.
In both cases no long options are supported.

diff --git a/dstore b/dstore
--- a/dstore
+++ b/dstore
@@ -133,43 +133,48 @@ __qc_fqname()
 [ ! -e "$QC_DSTORE_INDEX" ] && touch "$QC_DSTORE_INDEX"
 
 typeset delete=''
-typeset OPTIND o
 
-while getopts ":elcd-" o "$@"; do
-    case $o in
-        e)
+if ! _args="$(getopt -n "$script_name" -o "elcd" --long "help,version" -- "$@")"; then
+    echo >&2 "Try '$script_name --help' for more information."
+    exit 1
+fi
+eval "set -- $_args"
+
+while true; do
+    case $1 in
+        -e)
             ${VISUAL:-${EDITOR:-vi}} "$QC_DSTORE_INDEX"
             __dstore_clean warn
             exit
             ;;
-        l)
+        -l)
             cat "$QC_DSTORE_INDEX"
             exit
             ;;
-        c) __dstore_clean
+        -c) __dstore_clean
             exit
             ;;
-        d) delete=true
+        -d) delete=true
             ;;
-        -)
-            if [ "${!OPTIND}" = "--help" ]; then
-                show_help
-                exit 0
-            elif [ "${!OPTIND}" = "--version" ]; then
-                echo "$script_name - Quick Change Directory v$qc_version"
-                exit 0
-            else
-                echo >&2 "Invalid option '${!OPTIND:-}'" && echo >&2 ""
-                echo >&2 "Try '$script_name --help' for more information."
-                exit 1
-            fi
+        --help)
+            show_help
+            exit 0
+            ;;
+        --version)
+            echo "$script_name - Quick Change Directory v$qc_version"
+            exit 0
+            ;;
+        --)
+            shift
+            break
             ;;
         *)
-            echo >&2 "Invalid option '$OPTARG'"
+            echo >&2 "Invalid option '$1'"
             echo >&2 "Try '$script_name --help' for more information."
             exit 1
             ;;
     esac
+    shift
 done
 
 shift $((OPTIND-1))
diff --git a/qc-backend b/qc-backend
--- a/qc-backend
+++ b/qc-backend
@@ -378,6 +378,9 @@ updateIndex()
         for d in "$@"; do
             if [ "$d" = "-E" ]; then
                 ARGS+=( "-E" )
+            elif [ "$d" = "--" ]; then
+                # skip
+                :
             else
                 d="$(readlink -f "$d")"
                 ARGS+=( "-i" "$d")
@@ -499,8 +502,6 @@ complete_option()
 typeset grepOpt=""
 typeset indexSelect=""
 typeset printRegex=""
-typeset OPTIND
-typeset o
 
 PATH="$PATH:$QC_DIR"
 
@@ -511,75 +512,82 @@ if [ "${1:-}" = "--complete" ]; then
     complete_option "$@"
 fi
 
-while getopts ":ieEhHauUSlR-" o "$@"; do
-    case $o in
-        i) grepOpt="-i"
+if ! _args="$(getopt -n "qc" -o "ieEhHauUSlR" --long "help,version,config" -- "$@")"; then
+    echo >&2 "Try 'qc --help' for more information."
+    exit 1
+fi
+eval "set -- $_args"
+
+while true; do
+    case $1 in
+        -i) grepOpt="-i"
             ;;
-        a) indexSelect="${indexSelect}a"
+        -a) indexSelect="${indexSelect}a"
             ;;
-        h) indexSelect="${indexSelect}h"
+        -h) indexSelect="${indexSelect}h"
             ;;
-        H) indexSelect="${indexSelect}H"
+        -H) indexSelect="${indexSelect}H"
             ;;
-        e) indexSelect="${indexSelect}e"
+        -e) indexSelect="${indexSelect}e"
             ;;
-        E) indexSelect="${indexSelect}E"
+        -E) indexSelect="${indexSelect}E"
             ;;
-        u)
+        -u)
             [ -n "$cl_completion" ] && complete_local_dir "$@"
-            shift $((OPTIND-1))
+            shift
             updateIndex -E "$@" >&2
             exit 0
             ;;
-        U)
+        -U)
             [ -n "$cl_completion" ] && complete_local_dir "$@"
-            shift $((OPTIND-1))
+            shift
             updateIndex "$@" >&2
             exit 0
             ;;
-        S)
+        -S)
             [ -n "$cl_completion" ] && exit 1
             index_statistics
             exit 0
             ;;
-        l)
+        -l)
             [ -n "$cl_completion" ] && exit 1
             grep --color=always '^:[^ ]* ' "$QC_DSTORE_INDEX" >&2
             exit 0
             ;;
-        R) printRegex=true
+        -R) printRegex=true
             ;;
-        -)
-            if [ "${!OPTIND:-}" = "--help" ]; then
-                show_help >&2
-                exit 0
-            elif [ "${!OPTIND:-}" = "--version" ]; then
-                echo "qc - Quick Change Directory v$qc_version" >&2
-                exit 0
-            elif [ "${!OPTIND:-}" = "--config" ]; then
-                if [ ! -e "$QC_DIR/qc-index.cfg" ]; then
-                    echo >&2 "ERROR: $QC_DIR/qc-index.cfg does not exist."
-                    echo >&2 "       Use 'qc -u' to create a default config file."
-                    exit 1
-                fi
-                ${VISUAL:-${EDITOR:-vi}} "$QC_DIR/qc-index.cfg" </dev/tty >/dev/tty
-                exit 0
-            else
-                [ -n "$cl_completion" ] && exit 1
-                echo >&2 "Invalid option '${!OPTIND:-}'"
-                echo >&2 "Try 'qc --help' for more information."
+        --help)
+            [ -n "$cl_completion" ] && complete_local_dir "$@"
+            show_help >&2
+            exit 0
+            ;;
+        --version)
+            [ -n "$cl_completion" ] && complete_local_dir "$@"
+            echo "qc - Quick Change Directory v$qc_version" >&2
+            exit 0
+            ;;
+        --config)
+            [ -n "$cl_completion" ] && complete_local_dir "$@"
+            if [ ! -e "$QC_DIR/qc-index.cfg" ]; then
+                echo >&2 "ERROR: $QC_DIR/qc-index.cfg does not exist."
+                echo >&2 "       Use 'qc -u' to create a default config file."
                 exit 1
             fi
+            ${VISUAL:-${EDITOR:-vi}} "$QC_DIR/qc-index.cfg" </dev/tty >/dev/tty
+            exit 0
+            ;;
+        --) shift
+            break
             ;;
         *)
-                echo >&2 "Invalid option '$OPTARG'"
-                echo >&2 "Try 'qc --help' for more information."
-                exit 1
+            [ -n "$cl_completion" ] && exit 1
+            echo >&2 "Invalid option '$1'"
+            echo >&2 "Try 'qc --help' for more information."
+            exit 1
             ;;
     esac
+    shift
 done
-
-shift $((OPTIND-1))
 
 if [ -n "$printRegex" ]; then
     args2regex "$@" >&2
diff --git a/qc-build-index b/qc-build-index
--- a/qc-build-index
+++ b/qc-build-index
@@ -518,7 +518,7 @@ configure_crontab()
         return 0
     fi
     if [ -n "${1//[0-9]/}" ]; then
-        echo >&2 "ERROR: Invalid minutes value for '--cron'"
+        echo >&2 "ERROR: Invalid minutes value for '--cron': '$1'"
         return 1
     fi
     typeset -i minutes=$1
@@ -548,42 +548,55 @@ configure_crontab()
 #---------[ MAIN ]-------------------------------------------------------------
 
 typeset -a INC_UPD=()
-while getopts ":HEi:-" o "$@"; do
-    case $o in
-        i)
+
+if ! _args="$(getopt -n "$script_name" -o "iHE" --long "help,version,cron" -- "$@")"; then
+    echo >&2 "Try '$script_name --help' for more information."
+    exit 1
+fi
+eval "set -- $_args"
+
+while true; do
+    case $1 in
+        -i)
             d=$OPTARG
             d="${d%"${d##*[!/]}"}"
             INC_UPD+=( -i "$d" )
             ;;
-        H)
+        -H)
             ignHidden=true
             ;;
-        E)
+        -E)
             ignExt=true
             ;;
-        -)
-            if [ "${!OPTIND}" = "--help" ]; then
-                show_help
-                exit 0
-            elif [ "${!OPTIND}" = "--version" ]; then
-                echo "$script_name - Quick Change Directory v$qc_version"
-                exit 0
-            elif [ "${!OPTIND}" = "--cron" ]; then
-                shift
-                configure_crontab "${!OPTIND:-}"
-                exit
-            else
-                echo >&2 "Invalid option '${!OPTIND:-}'" && echo >&2 ""
-                echo >&2 "Try '$script_name --help' for more information."
+        --help)
+            show_help
+            exit 0
+            ;;
+        --version)
+            echo "$script_name - Quick Change Directory v$qc_version"
+            exit 0
+            ;;
+        --cron)
+            shift
+            if [ "$1" != "--" ] || [ "$#" -gt 2 ]; then
+                echo >&2 "Error: Invalid arguments for --cron"
                 exit 1
             fi
+            shift
+            configure_crontab "${1:-}"
+            exit
+            ;;
+        --)
+            shift
+            break
             ;;
         *)
-            echo >&2 "Invalid option '$OPTARG'"
+            echo >&2 "Invalid option '$1'"
             echo >&2 "Try '$script_name --help' for more information."
             exit 1
             ;;
     esac
+    shift
 done
 
 shift $((OPTIND-1))
