Prefer fd to find when scanning the directory tree
fd is faster than find.

diff --git a/qc-build-index b/qc-build-index
--- a/qc-build-index
+++ b/qc-build-index
@@ -33,6 +33,13 @@ QC_DSTORE_INDEX=$QC_DIR/index.dstore
 
 CFG="$QC_DIR/qc-index.cfg"
 
+if [[ -n "${QC_USE_FIND:-}" || -z "$(command -v fd)" ]]; then
+    QC_USE_FIND=true
+else
+    unset QC_USE_FIND
+fi
+
+
 show_help()
 {
     echo "USAGE:"
@@ -278,9 +285,164 @@ build_index()
 
     # find all directories excluding those configured
     # echo >&2 find "${ROOTS[@]}" -xdev -type d "${ignDirs[@]}" -prune -o -xtype d "${filter[@]}" -print
+    echo "Using find command"
     find "${ROOTS[@]}" "${MAX_DEPTH[@]}" -xdev -type d "${ignDirs[@]}" -prune -o -xtype d "${filter[@]}" -print >> "$NEW_INDEX"
     # Don't check exit code.
     # A "permission denied" in some subdir would kill the index
+
+    if [ -s "$NEW_INDEX" ]; then
+        # replace .qc/index with new content
+        mv -f "$NEW_INDEX" "$INDEX_FILE"
+
+        typeset dir_count
+        dir_count=$(wc -l < "$INDEX_FILE")
+
+        typeset UPD=''
+        if [ ${#INC_ROOTS[@]} -gt 0 ]; then
+            dir_diff=$((dir_count - inc_start))
+            UPD=" (Updated: $dir_diff)"
+        fi
+
+        echo "Stored $dir_count directory names$UPD."
+    else
+        rm -f "$NEW_INDEX"
+        echo "No directories found -- no index created."
+    fi
+}
+
+build_index_using_fd()
+{
+    typeset IDX_NAME=$1
+    shift
+
+    if [ "$IDX_NAME" != "$(basename "$IDX_NAME")" ]; then
+        echo >&2 "ERROR: Index name must be a plain filename: $IDX_NAME"
+        return 1
+    fi
+
+    typeset include_hidden=""
+    typeset -a FILTER=()
+    typeset -a INC_UPD=()
+    typeset -a FD_ARGS=()
+    typeset OPTARG OPTIND=0 d
+    while getopts ":f:i:d:h" o "$@"; do
+        case $o in
+            f) FILTER=( "${FILTER[@]}" "$OPTARG" )
+                ;;
+            i)
+                d=$OPTARG
+                d="${d%"${d##*[!/]}"}"
+                INC_UPD+=( "$d" )
+                ;;
+            d)
+                if [ -n "${OPTARG//[0-9]/}" ]; then
+                    echo >&2 "ERROR: Argument for -d not a number for $IDX_NAME"
+                    return 1
+                fi
+                FD_ARGS+=( "--max-depth" "$OPTARG" )
+                ;;
+            h)
+                include_hidden=true
+                ;;
+            *)
+                return 1
+                ;;
+        esac
+    done
+
+    shift $((OPTIND-1))
+
+    typeset -a ROOTS=()
+    while [ $# -gt 0 ]; do
+        if [ "$1" = "--" ]; then
+            shift
+            break
+        fi
+        if d="$(readlink -e "$1")"; then
+            ROOTS=( "${ROOTS[@]}" "$d" )
+        else
+            echo >&2 "ERROR: Root directory not found: $1"
+        fi
+        shift
+    done
+    if [ ${#ROOTS[@]} -eq 0 ]; then
+        echo >&2 "ERROR: No root directory"
+        return 1
+    fi
+
+    FD_PATTERN=".*"
+    typeset -a IGNORE_DIRS=()
+    case "$IDX_NAME" in
+        *.index.hidden) ;&
+        *.index.hidden.$HOSTNAME)
+            FD_ARGS+=( --hidden )
+            FD_PATTERN='.*/\..*'
+            ;;
+        *)
+            if [ -n "$include_hidden" ]; then
+                FD_ARGS+=( --hidden )
+            fi
+            ;;
+    esac
+
+    while [ $# -gt 0 ]; do
+        IGNORE_DIRS+=( --exclude "**/$1" --exclude "**/$1/**" )
+        shift
+    done
+
+    #echo "INDEX:  $IDX_NAME"
+    #echo "ROOTS:  ${ROOTS[@]}"
+    #echo "IGNORE: ${IGNORE_DIRS[@]}"
+    #echo "FILTER: ${FILTER[@]}"
+
+    [ ! -d "$QC_DIR" ] && mkdir "$QC_DIR"
+
+    typeset INDEX_FILE=$QC_DIR/$IDX_NAME
+
+    typeset -a INC_ROOTS=()
+    if [ ${#INC_UPD[@]} -gt 0 ]; then
+        if [ -e "$INDEX_FILE" ]; then
+            for d in "${INC_UPD[@]}"; do
+                if [ -d "$d" ]; then
+                    if is_descendant "$d" "${ROOTS[@]}"; then
+                        INC_ROOTS+=( "$d" )
+                        #else
+                        #    echo "WARN: Index $IDX_NAME does not contain $d -- ignored"
+                    fi
+                else
+                    echo "WARN: $d does not exist -- ignored"
+                fi
+            done
+            if [ ${#INC_ROOTS[@]} -eq 0 ]; then
+                if [ -z "$QC_LIST_UPD" ]; then
+                    echo >&2 "ERROR: Index $IDX_NAME does not contain any of [ ${INC_UPD[*]} ]"
+                    return 1
+                else
+                    echo "Skipping $IDX_NAME: does not contain any of [ ${INC_UPD[*]} ]"
+                    return 0
+                fi
+            fi
+        else
+            echo "Index $IDX_NAME does not exist -- ignoring incremental update"
+        fi
+    fi
+
+    typeset NEW_INDEX
+    NEW_INDEX=$(mktemp "${INDEX_FILE/.index/.updating-index}.XXXX")
+
+    # if incremental update set new ROOTS and prefill index file
+    if [ ${#INC_ROOTS[@]} -gt 0 ]; then
+        ROOTS=( "${INC_ROOTS[@]}" )
+        re=$(printf "%s|" "${ROOTS[@]}")
+        re=${re:0:-1}
+        grep -aEv "^($re)(/|$)" "$INDEX_FILE" > "$NEW_INDEX"
+    fi
+    typeset inc_start
+    inc_start=$(wc -l < "$NEW_INDEX")
+
+    # find all directories excluding those configured
+    echo "Using fd command"
+    fd -I --full-path -s --type d "${FD_ARGS[@]}" "${IGNORE_DIRS[@]}" "${FD_PATTERN}" "${ROOTS[@]}" >> "$NEW_INDEX"
 
     if [ -s "$NEW_INDEX" ]; then
         # replace .qc/index with new content
@@ -497,8 +659,14 @@ while IFS= read -r line; do
     fi
 
     echo "Updating ${ARGS[0]}..."
-    if ! build_index "${ARGS[@]}"; then
-        printf >&2 '%s[%d] ERROR: Building index failed.\n' "$CFG" "$lno"
+    if [ -n "${QC_USE_FIND:-}" ]; then
+        if ! build_index "${ARGS[@]}"; then
+            printf >&2 '%s[%d] ERROR: Building index failed.\n' "$CFG" "$lno"
+        fi
+    else
+        if ! build_index_using_fd "${ARGS[@]}"; then
+            printf >&2 '%s[%d] ERROR: Building index failed.\n' "$CFG" "$lno"
+        fi
     fi
 
 done < "$CFG"
